#!/usr/bin/env php
<?php
/*
 * This file is part of the jinyPHP package.
 *
 * (c) hojinlee <infohojin@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

define('START', microtime(true));
const DS = DIRECTORY_SEPARATOR;

require_once "./vendor/autoload.php";

new \Jiny\Lamp\CLI($argv);